# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/scrape.ui',
# licensing of 'gui/scrape.ui' applies.
#
# Created: Tue Mar 26 09:51:17 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dir_label = QtWidgets.QLabel(self.centralwidget)
        self.dir_label.setObjectName("dir_label")
        self.verticalLayout_2.addWidget(self.dir_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.download_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.download_dir.setObjectName("download_dir")
        self.horizontalLayout_2.addWidget(self.download_dir)
        self.dir_button = QtWidgets.QToolButton(self.centralwidget)
        self.dir_button.setObjectName("dir_button")
        self.horizontalLayout_2.addWidget(self.dir_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.search_label = QtWidgets.QLabel(self.centralwidget)
        self.search_label.setObjectName("search_label")
        self.verticalLayout_2.addWidget(self.search_label)
        self.search_layout = QtWidgets.QVBoxLayout()
        self.search_layout.setObjectName("search_layout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_bar = QtWidgets.QLineEdit(self.centralwidget)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_3.addWidget(self.search_bar)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_3.addWidget(self.search_button)
        self.search_layout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.search_layout)
        self.info_text = QtWidgets.QLabel(self.centralwidget)
        self.info_text.setObjectName("info_text")
        self.verticalLayout_2.addWidget(self.info_text)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.song_box = QtWidgets.QHBoxLayout()
        self.song_box.setObjectName("song_box")
        self.picture_label = QtWidgets.QLabel(self.centralwidget)
        self.picture_label.setText("")
        self.picture_label.setPixmap(QtGui.QPixmap("../../../Downloads/hqdefault.jpg"))
        self.picture_label.setObjectName("picture_label")
        self.song_box.addWidget(self.picture_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.song_name_label = QtWidgets.QLabel(self.centralwidget)
        self.song_name_label.setObjectName("song_name_label")
        self.verticalLayout.addWidget(self.song_name_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.change_search_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_search_button.setObjectName("change_search_button")
        self.horizontalLayout_5.addWidget(self.change_search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.song_box.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.song_box)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.progress_label = QtWidgets.QLabel(self.centralwidget)
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout_2.addWidget(self.progress_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout.addWidget(self.progress_bar)
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout.addWidget(self.download_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "scrape", None, -1))
        self.dir_label.setText(QtWidgets.QApplication.translate("MainWindow", "Download Directory", None, -1))
        self.download_dir.setText(QtWidgets.QApplication.translate("MainWindow", "default_directory", None, -1))
        self.dir_button.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.search_label.setText(QtWidgets.QApplication.translate("MainWindow", "Download Song", None, -1))
        self.search_button.setText(QtWidgets.QApplication.translate("MainWindow", "Search", None, -1))
        self.info_text.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>text_here</p></body></html>", None, -1))
        self.song_name_label.setText(QtWidgets.QApplication.translate("MainWindow", "song_name", None, -1))
        self.change_search_button.setText(QtWidgets.QApplication.translate("MainWindow", "Not correct?", None, -1))
        self.progress_label.setText(QtWidgets.QApplication.translate("MainWindow", "Downloading song 1/1 (song_name)", None, -1))
        self.download_button.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))

